### ISSUE TITLE
Refactor/ Features

### ISSUE THREAD

**Issue by A2va** [A2va/xmake-vscode#6]
Features:

- [x] Debugger with `launch.json` #1
- [ ] Improve C++ completion and configuration #2 
- [ ] Task provider #4
- [ ] Xmake LSP #7 

Refactor:
- [ ] Rewrite Xmake class
- [ ] Refactor lua script #3, wait until #3 is implemented
- [ ] Improve start up time with [bundler](https://code.visualstudio.com/api/working-with-extensions/bundling-extension#run-webpack), currently start up is around 300ms. Some heavy extensions, like GitLens are < 200ms.
